command_key = "@"
use_nerdfont = false
notify = true

[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "light white"
playing = "red"
playing_selected = "red"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "light white"
statusbar_bg = "black"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
